### ISSUE TITLE
Errors occurred while training and evaluating the model  During training: TypeError:__ init__ () missing 2 required keyword-only arguments: 'bg_ cls_ loss_ weight' and 'openset_ test'  When profiling: KeyError: 'naiveSyncBN_ N'

### ISSUE THREAD

**Issue by Originlightwkp** [xiaofeng94/VL-PLM#9]
During training：

Traceback (most recent call last):
  File "train_net.py", line 246, in <module>
    args=(args,),
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 203, in main
    model = build_model(cfg)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 174, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 229, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/modeling/meta_arch/rcnn.py", line 87, in from_config
    "roi_heads": build_roi_heads(cfg, backbone.output_shape()),
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 43, in build_roi_heads
    return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 174, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 229, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 620, in from_config
    ret.update(cls._init_box_head(cfg, input_shape))
  File "/media/cheng/dataset4/explotingunlabeled/VL_PLM/modeling/roi_heads/roi_heads.py", line 18, in _init_box_head
    ret['box_predictor'] = VLPLMFastRCNNOutputLayers(cfg, ret['box_head'].output_shape)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 175, in wrapped
    init_func(self, **explicit_args)
  File "/media/cheng/dataset4/explotingunlabeled/VL_PLM/modeling/roi_heads/box_predictor.py", line 68, in __init__
    loss_weight=loss_weight)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 177, in wrapped
    init_func(self, *args, **kwargs)
TypeError: __init__() missing 2 required keyword-only arguments: 'bg_cls_loss_weight' and 'openset_test'

During evaluation：

raceback (most recent call last):
  File "train_net.py", line 246, in <module>
    args=(args,),
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 203, in main
    model = build_model(cfg)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 174, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 229, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/modeling/meta_arch/rcnn.py", line 87, in from_config
    "roi_heads": build_roi_heads(cfg, backbone.output_shape()),
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 43, in build_roi_heads
    return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 174, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 229, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 620, in from_config
    ret.update(cls._init_box_head(cfg, input_shape))
  File "/media/cheng/dataset4/explotingunlabeled/VL_PLM/modeling/roi_heads/roi_heads.py", line 16, in _init_box_head
    ret = super()._init_box_head(cfg, input_shape)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 654, in _init_box_head
    cfg, ShapeSpec(channels=in_channels, height=pooler_resolution, width=pooler_resolution)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/box_head.py", line 118, in build_box_head
    return ROI_BOX_HEAD_REGISTRY.get(name)(cfg, input_shape)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 175, in wrapped
    init_func(self, **explicit_args)
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/box_head.py", line 59, in __init__
    norm=get_norm(conv_norm, conv_dim),
  File "/media/cheng/dataset4/annaconda3/envs/clip/lib/python3.7/site-packages/detectron2-RegionCLIP-py3.7-linux-x86_64.egg/detectron2/layers/batch_norm.py", line 161, in get_norm
    }[norm]
KeyError: 'naiveSyncBN_N'

someone can help me?

**Comment by Feeeeeel** [comment]
I also encountered these two errors...

**Comment by xiaofeng94** [comment]
Hey guys, I thought those may be caused by your environment setup.

**Comment by Feeeeeel** [comment]
Yep, I encountered this issue without installing detecton2
When I recreate the environment and install detectron2, the problem is resolved
